<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="./CSS/estilo.css">
    <title> HOME </title>
  
  <body>
  
  <DIV ID= "CONTENEDOR">

<DIV ID= "ENCABEZADO">
    <H1> SISTEMA DE GESTIÓN ODONTOLÓGICA </H1>
</DIV>

<UL ID="MENU">
    <LI> <A HREF="INDEX.PHP"> INICIO </A> </LI>
    <LI> <A HREF=".#"> NOSOTROS </A> </LI>
    <LI> <A HREF="#"> PERSONAL  </A></LI>
    <LI> <A HREF="#"> TRATAMIENTOS</A>   </LI>    
    <LI> <A HREF="#"> CONTACTO </A></LI>
    <LI> <A HREF="LOGIN/REGISTRATE.PHP"> REGISTRATE </A></LI>
    <LI> <A HREF="LOGIN/LOGIN.PHP"> INICIAR SESIÓN </A><LI>
                     
</UL> 
  

  <DIV ID="CONTENIDO">

      
          <BR>      
            <center> <img src="img/1.jpg" width="90%" height="700">
    </DIV>
        
    <DIV ID="FOOTER">
		
    <P>  SENA - CEGAFE - TUNJA
    <BR>TGO. EN ANALISIS Y DESARROLLO DE SISTEMAS DE INFORMACION  
    <BR> ELABORADO POR: DANIEL ALEXANDER ROJAS ACEVEDO 
    <BR> danirojas473@gmail.com
  </P>
</div>
</DIV>
  </body>
</html>